### ISSUE TITLE
Failed to execute with default given commands

### ISSUE THREAD

**Issue by mritunjaymusale** [keroro824/HashingDeepLearning#32] opened 2020-05-11 22:11 UTC
I followed the steps mentioned on readme. I got  the following :
./runme ../SLIDE/Config_amz.csv    

new Network
new Layer
new Node array
[1]    2402 segmentation fault (core dumped)  ./runme ../SLIDE/Config_amz.csv

I did adjust the config file as well and removed `-mavx512f` from Makefile

**Comment by robers97** [comment] 2020-06-11 17:29
dupe of issue 27... there is a default NULL initiation of saved_weights file str that will cause CNPY to barf.   That should be a check in main.cpp aka: 

        if(savedWeights=="") {
                std::cout << "Will not save weights as configuration file does not specify savedWeight file..." << std::endl;
        } else {
        _mynet->saveWeights(savedWeights);
        }

But otherwise, just put a line in your config file to give it a non-NULL value.

**Comment by mritunjaymusale** [comment] 2020-06-13 16:11
Actually I managed to overcome this from one of the forked repos 
https://github.com/hieuhoang/HashingDeepLearning
This fork ran with no issues

**Closed as completed** 2020-06-18 11:28 UTC
